project:
  type: book

execute:
  freeze: auto
  
book:
  title: "Longitudinal A4 & Gene Expression Project"
  author: "Hannah Klinger"
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
<<<<<<< HEAD
    # - demographics.qmd
    # - visualizations.qmd
    # - manhattan_plots.qmd
    # - part: pacc_analyses.qmd
    #   chapters:
    #     - pacc_sensitivity_sexstratified.qmd
    #     - pacc_sensitivity_ptauinteract.qmd
    #     - pacc_sensitivity_treatvsplacebo.qmd
    # - part: bl_ptau_analyses.qmd 
      
=======
    - demographics.qmd
    - visualizations.qmd
    - manhattan_plots.qmd
    - part: pacc_analyses.qmd
      chapters:
        - pacc_sensitivity_sexstratified.qmd
        - pacc_sensitivity_ptauinteract.qmd
        - pacc_sensitivity_treatvsplacebo.qmd
>>>>>>> origin/main


format:
  html:
    self-contained: true
    theme: cosmo
    number-sections: false
  # pdf:
  #   documentclass: scrreprt

editor: visual


